openapi: 3.0.0
info:
  title: Route Management API
  version: 0.0.1
  description: RESTful API для управления коллекцией объектов класса Route

servers:
  - url: https://localhost:8080/route-management
    x-environment: local
  - url: https://89.169.147.9:8080/route-management
    x-environment: prod
    
paths:
  /routes:
    get:
      summary: Получить список маршрутов с возможностью сортировки, фильтрации и пагинации
      tags:
        - Routes
      operationId: getRoutes
      parameters:
        - name: limit
          in: query
          description: Количество элементов в выдаче
          required: false
          schema:
            type: integer
            minimum: 1
            example: 10
        - name: offset
          in: query
          description: Сдвиг по элементам от начала
          required: false
          schema:
            type: integer
            minimum: 1
            example: 10
        - $ref: '#/components/parameters/SortBy'
        - name: filter
          in: query
          description: Параметры для сортировки
          required: false
          schema:
            type: object
            properties:
              locationIdFrom:
                description: Id локации откуда
                type: integer
                minimum: 1
                format: int64
                example: 25
              locationIdTo:
                description: Id локации куда
                type: integer
                minimum: 1
                format: int64
                example: 25
              minId:
                description: Минимальный id маршрута
                type: integer
                minimum: 1
                format: int32
                example: 25
              maxId:
                  description: Максимальный id маршрута
                  minimum: 1
                  type: integer
                  format: int32
                  example: 52
              name:
                description: Название маршрута
                type: string
                minLength: 1
              minX:
                description: Минимальная координата х
                type: integer
                format: int32
                example: -1
              maxX:
                description: Максимальная координата х
                type: integer
                format: int32
                example: 1
              minY:
                description: Минимальная координата y
                type: number
                format: double
                example: -1337.3
              maxY:
                description: Максимальная координата y
                type: number
                format: double
                example: 1337.3
              minCreationDate:
                description: Дата создания должна быть позже
                type: string
                format: date-time
                nullable: false
                example: 2003-10-17T11:02:15Z
              maxCreationDate:
                description: Дата создания должна быть раньше или равна
                type: string
                format: date-time
                nullable: false
                example: 2024-10-17T11:02:15Z
              fromLocationX:
                description: Минимальное координата X откуда
                type: integer
                format: int32
              toLocationX:
                description: Максимальная координата X откуда
                type: integer
                format: int32
              fromLocationY:
                description: Минимальное координата Y откуда
                type: integer
                format: int32
              toLocationY:
                description: Максимальная координата Y откуда
                type: integer
                format: int32
              fromLocationZ:
                description: Координата Z откуда
                type: integer
                format: int64
              toLocationZ:
                description: Координата Z куда
                type: integer
                format: int64
              distance:
                description: Дистанция маршрута
                type: number
                format: double
              nameStartsWithSubstr:
                description: Имя маршрута начинается с заданной подстроки
                type: string
                minLength: 1
      responses:
        '200':
          description: Успешный ответ с массивом маршрутов
          content:
            application/json:
              schema:
                title: RouteResponse
                type: object
                properties:
                  routes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Route'
                  total:
                    type: integer
                    description: Общее количество элементов
                  limit:
                    type: integer
                    description: Количество элементов
                  offset:
                    type: integer
                    description: Сдвиг по элементам
        '204':
          $ref: '../../common/responses.yaml#/components/responses/204'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'

    post:
      summary: Добавить новый маршрут
      tags:
        - Routes
      operationId: postRoute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteUpsertRequest'
      responses:
        '201':
          description: Маршрут успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'
    

  /routes/{id}:
    get:
      summary: Получить маршрут по ID
      tags:
        - Routes
      operationId: getRouteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Информация о маршруте
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'
          
            
    put:
      summary: Обновить маршрут по ID
      tags:
        - Routes
      operationId: updateRouteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteUpsertRequest'
      responses:
        '200':
          description: Маршрут успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'

    delete:
      summary: Удалить маршрут по ID
      tags:
        - Routes
      operationId: deleteRouteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
        - name: distance
          in: query
          description: Удалить маршрут с указанным значением distance
          schema:
            type: number
      responses:
        '204':
          description: Маршрут успешно удален (если найден)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'
  
  /routes/distances/{distance}:
    delete:
      summary: Удалить либой маршрут с дистанцией равной заданной
      tags:
        - Routes
      operationId: deleteRouteByDistance
      parameters:
        - name: distance
          in: path
          required: true
          description: Удалить маршрут с указанным значением distance
          schema:
            type: number
            format: double
      responses:
        204':
          description: Маршрут успешно удален (если найден)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
            $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'

  /routes/count:
    get:
      summary: Получить количество маршрутов, удовлетворяющих критериям
      tags:
        - Routes
      operationId: getRoutesCounts
      parameters:
        - name: maxDistance
          in: query
          description: Максимальное значение меньше distance
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Количество маршрутов, удовлетворяющих критериям
          content:
            application/json:
              schema:
                type: integer
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'

  /locations:
    get:
      summary: Получить локацию по идентификатору
      tags:
        - Locations
      operationId: getLocationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
      responses:
        '200':
          description: Локация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'
components:
  parameters:
    SortBy:
      name: sortBy
      in: query
      description: Параметры для сортировки
      required: false
      schema:
        type: array
        items:
          type: string
          description: Если перед полем стоит '-', то сортировка по убыванию, иначе по возрастанию
          $ref: '#/components/schemas/SortFields'
        example: name
  schemas:
    SortFields:
      type: string
      enum:
        - Id
        - Name
        - Coordinates
        - CreationDate
        - From
        - To
        - Distance
        - -Id
        - -Name
        - -Coordinates
        - -CreationDate
        - -From
        - -To
        - -Distance
    Route:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор маршрута
          readOnly: true
          minimum: 1
          format: int64
          nullable: false
        name:
          type: string
          description: Название маршрута
          minLength: 1
          nullable: false
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
          readOnly: true
          nullable: false
        from:
          $ref: '#/components/schemas/Location'
        to:
          $ref: '#/components/schemas/Location'
        distance:
          $ref: '#/components/schemas/Distance'
      required:
        - id
        - name
        - coordinates
        - creationDate
        - distance
        
    RouteUpsertRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        from:
          $ref: '#/components/schemas/Location'
        to:
          $ref: '#/components/schemas/Location'
        distance:
          $ref: '#/components/schemas/Distance'
      required:
        - name
        - coordinates
        - distance

    Coordinates:
      type: object
      nullable: true
      properties:
        x:
          type: integer
          format: int32
          nullable: false
        y:
          type: number
          maximum: 610
          format: double
          nullable: false
      required:
        - x
        - y

    Location:
      type: object
      nullable: true
      properties:
        x:
          type: integer
          format: int32
          nullable: false
        y:
          type: integer
          format: int32
          nullable: true
        z:
          type: integer
          format: int64
          nullable: false
        name:
          type: string
          nullable: true
          maxLength: 517
      required:
        - x
        - z
    
    Distance:
      description: Дистанция до маршрута
      type: number
      format: double
      minimum: 1
      nullable: false