openapi: 3.0.0
info:
  title: Route Management API
  version: 0.0.1
  description: RESTful API для управления коллекцией объектов класса Route

servers:
  - url: https://localhost:8080/route-management
    x-environment: local
  - url: https://89.169.147.9:8080/route-management
    x-environment: prod
    
paths:
  /routes:
    get:
      summary: Получить список маршрутов с возможностью сортировки, фильтрации и пагинации
      tags:
        - Routes
      operationId: getRoutes
      parameters:
        - name: limit
          in: query
          description: Количество элементов в выдаче
          required: false
          schema:
            type: integer
            minimum: 1
            example: 10
        - name: offset
          in: query
          description: Сдвиг по элементам от начала
          required: false
          schema:
            type: integer
            minimum: 1
            example: 10
        - $ref: './client-models.yaml#/components/parameters/SortBy'
        - $ref: './client-models.yaml#/components/parameters/Filter'
      responses:
        '200':
          description: Успешный ответ с массивом маршрутов
          content:
            application/json:
              schema:
                title: RouteResponse
                type: object
                properties:
                  routes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Route'
                  total:
                    type: integer
                    description: Общее количество элементов
                  limit:
                    type: integer
                    description: Количество элементов
                  offset:
                    type: integer
                    description: Сдвиг по элементам
        '204':
          $ref: '../../common/responses.yaml#/components/responses/204'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'

    post:
      summary: Добавить новый маршрут
      tags:
        - Routes
      operationId: postRoute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './client-models.yaml#/components/schemas/RouteUpsertRequest'
      responses:
        '201':
          description: Маршрут успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'
    

  /routes/{id}:
    get:
      summary: Получить маршрут по ID
      tags:
        - Routes
      operationId: getRouteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Информация о маршруте
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'
          
            
    put:
      summary: Обновить маршрут по ID
      tags:
        - Routes
      operationId: updateRouteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './client-models.yaml#/components/schemas/RouteUpsertRequest'
      responses:
        '200':
          description: Маршрут успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'

    delete:
      summary: Удалить маршрут по ID
      tags:
        - Routes
      operationId: deleteRouteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
        - name: distance
          in: query
          description: Удалить маршрут с указанным значением distance
          schema:
            type: number
      responses:
        '204':
          description: Маршрут успешно удален (если найден)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'
  
  /routes/distances/{distance}:
    delete:
      summary: Удалить любой маршрут с дистанцией равной заданной
      tags:
        - Routes
      operationId: deleteRouteByDistance
      parameters:
        - name: distance
          in: path
          required: true
          description: Удалить любой маршрут с указанным значением distance
          schema:
            type: number
            format: double
      responses:
        204':
          description: Маршрут успешно удален (если найден)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
            $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'

  /routes/count:
    get:
      summary: Получить количество маршрутов, удовлетворяющих критериям
      tags:
        - Routes
      operationId: getRoutesCounts
      parameters:
        - name: maxDistance
          in: query
          description: Максимальное значение меньше distance
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Количество маршрутов, удовлетворяющих критериям
          content:
            application/json:
              schema:
                type: integer
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'

  /locations/{id}:
    get:
      summary: Получить локацию по идентификатору
      tags:
        - Locations
      operationId: getLocationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
      responses:
        '200':
          description: Локация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '400':
          $ref: '../../common/responses.yaml#/components/responses/400'
        '404':
          $ref: '../../common/responses.yaml#/components/responses/404'
        '500':
          $ref: '../../common/responses.yaml#/components/responses/500'
        '503':
          $ref: '../../common/responses.yaml#/components/responses/503'
components:
  schemas:
    Route:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор маршрута
          readOnly: true
          minimum: 1
          format: int64
          nullable: false
        name:
          type: string
          description: Название маршрута
          minLength: 1
          nullable: false
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
          readOnly: true
          nullable: false
        from:
          $ref: '#/components/schemas/Location'
        to:
          $ref: '#/components/schemas/Location'
        distance:
          $ref: '#/components/schemas/Distance'
      required:
        - id
        - name
        - coordinates
        - creationDate
        - distance


    Coordinates:
      type: object
      nullable: true
      properties:
        x:
          type: integer
          format: int32
          nullable: false
        y:
          type: number
          maximum: 610
          format: double
          nullable: false
      required:
        - x
        - y

    Location:
      type: object
      nullable: true
      properties:
        x:
          type: integer
          format: int32
          nullable: false
        y:
          type: integer
          format: int32
          nullable: true
        z:
          type: integer
          format: int64
          nullable: false
        name:
          type: string
          nullable: true
          maxLength: 517
        id: 
          type: integer
          format: int32
      required:
        - x
        - z
    
    Distance:
      description: Дистанция до маршрута
      type: number
      format: double
      minimum: 1
      nullable: false