server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:soa.keystore # Хранилище ключей
    key-store-password: password # Пароль от хранилища ключей
    key-alias: soa # Псевдоним сертификата
    key-password: password # Пароль от ключа
    trust-store: classpath:soa.truststore # Хранилище доверенных сертификатов
    trust-store-password: password # Пароль от truststore

spring:
  application:
    name: route-management
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL=DEBUG: