client:
  route-management:
    server:
      name: route-management
      url: http://localhost:8082
      connect-timeout: 5000
      read-timeout: 10000
#    tls:
#      group: ''
#      trustAny: true