client:
  route-management:
    server:
      name: route-management
      url: https://localhost:8443/route-management-service-1
      connect-timeout: 5000
      read-timeout: 10000
#    tls:
#      group: ''
#      trustAny: true