spring:
  application:
    name: navigator
  main:
    banner-mode: "off"
server:
  port: 1516
server.http.port: 1616
logging:
  level:
    root: INFO
  org:
    springframework: DEBUG
    glassfish: DEBUG